name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  compute: ^1.0.2
  cron: ^0.6.1
  dart_frog: ^1.1.0
  dio: ^5.7.0
  mongo_dart: ^0.10.4

dev_dependencies:
  build_runner: ^2.4.13
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
